name: FormalGeo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - libffi
  - libsqlite
  - libzlib
  - ncurses
  - openssl
  - pip
  - python=3.11
  - readline=8.2
  - setuptools
  - tk=8.6.13
  - wheel
  - xz=5.2.6
  - pip:
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==24.1.0
      - boto==2.49.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - filelock==3.15.4
      - fonttools==4.53.1
      - formalgeo==0.0.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - func-timeout==4.3.5
      - git-filter-repo==2.47.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.3
      - numpy==2.0.1
      - openai==0.28.0
      - packaging==24.1
      - pandas==2.2.2
      - patsy==1.0.1
      - pillow==10.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2024.1
      - requests==2.32.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - six==1.16.0
      - sniffio==1.3.1
      - statsmodels==0.14.4
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.4.0
      - tqdm==4.66.4
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - yarl==1.9.4
      - z3==0.2.0
      - z3-solver==4.14.1.0
