name: Python Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        init-shell: bash
        cache-environment: false
        
    - name: Install testing dependencies
      shell: bash -el {0}
      run: |
        python -m pip install pytest pytest-cov
        
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        pytest
        
    - name: Generate coverage report
      shell: bash -el {0}
      run: |
        pytest --cov=src